#!/bin/bash

set -e

if [[ -n "${GT_SITE_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0") COMMAND OPTION[S]
Run tests
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
        exit 0
    fi
        shellcheck "${DIR}"/*
fi