#!/bin/bash

set -e

if [[ -n "${GT_SITE_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0") COMMAND OPTION[S]
Execute Terraform subcommands with remote state management.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
        exit 0
    fi

    if [[ -n "${GT_SITE_SETTINGS_BUCKET}" ]]; then
        pushd "${DIR}/../terraform"

        case "${1}" in
            plan)
                rm -rf .terraform terraform.tfstate*
                terraform init \
                          -backend-config="bucket=${GT_SITE_SETTINGS_BUCKET}" \
                          -backend-config="key=terraform/core/state"
                terraform plan \
                          -out="${GT_SITE_SETTINGS_BUCKET}.tfplan"
                ;;
            apply)
                terraform apply "${GT_SITE_SETTINGS_BUCKET}.tfplan"
                ;;
            *)
                echo "ERROR: I don't have support for that Terraform subcommand!"
                exit 1
                ;;
        esac

        popd
    else
        echo "ERROR: No GT_SITE_SETTINGS_BUCKET variable defined."
        exit 1
    fi
fi
