---
- hosts: all

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - role: "azavea.docker"
    - role: "azavea.terraform"
    - role: "azavea.aws-cli"
    - role: "gtsite.docker-compose"
